AMREX_HOME = ../../amrex

DEBUG	= FALSE

DIM	= 3

COMP    = gnu

USE_CUDA  = FALSE
USE_HIP   = TRUE
USE_DPCPP = FALSE

USE_MPI   = FALSE
USE_OMP   = FALSE

BL_NO_FORT = TRUE

TINY_PROFILE = FALSE

PRECISION = FLOAT

include $(AMREX_HOME)/Tools/GNUMake/Make.defs

include ./Make.package
include $(AMREX_HOME)/Src/Base/Make.package

include $(AMREX_HOME)/Tools/GNUMake/Make.rules
